DROP DATABASE IF EXISTS SimplePlotPaths;

CREATE DATABASE SimplePlotPaths;

USE SimplePlotPaths;

CREATE TABLE CLIENTS_CHARTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    USERS_ID varchar(100),
    CHART_ID varchar(20) UNIQUE,
    CHART_EXTENSION varchar(10),
    CHART_TYPE varchar(20),
    FILEPATH_TO_CHART varchar(250) UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX users_id_idx ON CLIENTS_CHARTS (USERS_ID);