services:
  ui:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      mycharts-network:
        ipv4_address: 10.0.1.196

networks:
  mycharts-network:
    external: true
    name: mycharts-network