services:
  scarlet:
    build:
      context: .
      dockerfile: Dockerfile.scarlet
    depends_on:
      database:
        condition: service_healthy
    networks:
      mycharts-network:
        ipv4_address: 10.0.1.55

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "8100:80"
    networks:
      mycharts-network:
        ipv4_address: 10.0.1.54

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost --silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      mycharts-network:
        ipv4_address: 10.0.1.113

networks:
  mycharts-network:
    external: true
    name: mycharts-network