FROM python:slim-buster
RUN mkdir -p src
WORKDIR /src
RUN mkdir storage
RUN mkdir tmp
COPY /requirements.txt .
RUN pip install -r requirements.txt
COPY . /src
RUN rm Dockerfile.database
RUN rm Dockerfile.proxy
RUN rm Dockerfile.irene
RUN rm init.sql
RUN rm nginx.conf
EXPOSE 5000
CMD ["flask", "--app", "app", "run", "--host", "0.0.0.0"]