services:
  authserver:
    build: 
      context: .
      dockerfile: Dockerfile.authserver
    depends_on:
      - redis
      - proxy
    networks:
      mycharts-network:
        ipv4_address: 10.0.1.120

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    networks:
      mycharts-network:
        ipv4_address: 10.0.1.15

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    networks:
      mycharts-network:
        ipv4_address: 10.0.1.20


networks:
  mycharts-network:
    external: true
    name: mycharts-network
