-- Initialize script to create tables for sqlite3 charts databse

DROP TABLE IF EXISTS USERS_CHARTS;

CREATE TABLE USERS_CHARTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERS_ID TEXT NOT NULL,
    CHART_ID TEXT UNIQUE NOT NULL,
    CHART_EXTENSION TEXT NOT NULL,
    CHART_TYPE TEXT NOT NULL,
    FILEPATH_TO_CHART TEXT NOT NULL,
    DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_USER_ID ON USERS_CHARTS(USERS_ID);
CREATE INDEX IDX_CHART_TYPE ON USERS_CHARTS(CHART_TYPE);
CREATE INDEX IDX_CHART_ID ON USERS_CHARTS(CHART_ID);
CREATE INDEX IDX_CHART_EXTENSION ON USERS_CHARTS(CHART_EXTENSION);

